version: "3.8"

services:
  wizzgeeks-leave-backend:
    build:
      context: ../office_leave_management_backend
      dockerfile: Dockerfile
    image: leave-backend
    ports:
      - "9051:9051"
    env_file:
      - ../office_leave_management_backend/.env
    networks:
      - attendance-network

  wizzgeeks-leave-frontend:
    build:
      context: ../office_leave_management_frontend
      dockerfile: Dockerfile
    image: leave-frontend
    ports:
      - "9050:9050"

    depends_on:
      - wizzgeeks-leave-backend
    networks:
      - attendance-network

networks:
  attendance-network:
    external: true
