version: "3.8"

services:
  office_backend:
    build:
      context: ../office_leave_management_backend
      dockerfile: Dockerfile
    image: office-app/office_backend
    ports:
      - "8000:8000"
    env_file:
      - ../office_leave_management_backend/.env
    networks:
      - shared-app-network

  office_frontend:
    build:
      context: ../office_leave_management_frontend
      dockerfile: Dockerfile
    image: office-app/office_frontend
    ports:
      - "80:80"
    networks:
      - shared-app-network



networks:
  shared-app-network:
    external: true

